[package]
name = "bundle_repo"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19"
tempfile = "3.3"
url = "2.2"
clap = { version = "4.1", features = ["derive"] }
regex = "1"

[features]
default = []
