[package]
name = "bundle_repo"
version = "0.1.0"
description = "Pack a local or remote Git Repository for LLM Consumption."
edition = "2021"
authors = ["Grant Ramsay <seapagan@gmail.com>"]
license = "MIT"
homepage = "https://seapagan.github.io/bundle-repo/"
exclude = [".github/*", "docs/*"]

[[bin]]
name = "bundlerepo"
path = "src/main.rs"

[dependencies]
git2 = "0.19"
tempfile = "3.3"
url = "2.2"
clap = { version = "4.1", features = ["derive"] }
regex = "1"
ignore = "0.4"
xml = "0.8"

[features]
default = []
